import { Product } from './types';

export const ALL_PRODUCTS: Product[] = [
  // Women
  {
    id: '1',
    name: 'Royal Blue Banarasi Saree',
    price: 250,
    image: 'https://images.pexels.com/photos/15945391/pexels-photo-15945391/free-photo-of-a-woman-in-a-traditional-indian-sari-and-jewelry.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'A stunning royal blue Banarasi silk saree with intricate gold zari work, perfect for weddings and festive occasions.',
    category: 'popular',
    demographic: 'women',
    productType: 'saree',
  },
  {
    id: '2',
    name: 'Elegant Red Anarkali Suit',
    price: 180,
    image: 'https://images.pexels.com/photos/11520630/pexels-photo-11520630.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'A floor-length Anarkali suit in a rich red georgette fabric, adorned with delicate embroidery. Comes with a matching dupatta.',
    category: 'new',
    demographic: 'women',
    productType: 'suit',
  },
  {
    id: '3',
    name: 'Pastel Green Lehenga Choli',
    price: 320,
    image: 'https://images.pexels.com/photos/16888463/pexels-photo-16888463/free-photo-of-woman-in-traditional-clothing-posing-outdoors.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'A beautiful pastel green lehenga with mirror work and a contrasting pink choli. Ideal for a modern yet traditional look.',
    category: 'best',
    demographic: 'women',
    productType: 'lehenga',
  },
  {
    id: '4',
    name: 'Simple Cotton Kurta',
    price: 60,
    image: 'https://images.pexels.com/photos/11269389/pexels-photo-11269389.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'A comfortable and stylish pink cotton kurta for daily wear, featuring block print patterns.',
    category: 'none',
    demographic: 'women',
    productType: 'kurta',
  },

  // Men
  {
    id: '5',
    name: 'Classic Cream Sherwani',
    price: 350,
    image: 'https://images.pexels.com/photos/10357606/pexels-photo-10357606.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'An exquisite cream-colored sherwani in raw silk, embellished with subtle gold embroidery. Perfect for the groom.',
    category: 'best',
    demographic: 'men',
    productType: 'sherwani',
  },
  {
    id: '6',
    name: 'Navy Blue Silk Kurta Set',
    price: 120,
    image: 'https://images.pexels.com/photos/10776363/pexels-photo-10776363.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'A smart navy blue silk kurta with a churidar pajama. A versatile outfit for any festive occasion.',
    category: 'popular',
    demographic: 'men',
    productType: 'kurta',
  },

  // Girls
  {
    id: '7',
    name: 'Bright Yellow Girls Lehenga',
    price: 90,
    image: 'https://images.pexels.com/photos/16500003/pexels-photo-16500003/free-photo-of-a-girl-in-a-yellow-dress-is-posing-for-a-picture.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'A cheerful yellow and pink lehenga choli for girls, made with soft net fabric. Light and comfortable for kids.',
    category: 'new',
    demographic: 'girl',
    productType: 'lehenga',
  },
  {
    id: '8',
    name: 'Girls Floral Print Kurta Set',
    price: 55,
    image: 'https://images.pexels.com/photos/5690924/pexels-photo-5690924.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'A cute floral print kurta and palazzo set for girls. Made from breathable cotton fabric.',
    category: 'none',
    demographic: 'girl',
    productType: 'kurta',
  },

  // Boys
  {
    id: '9',
    name: 'Maroon Kurta Pajama for Boys',
    price: 65,
    image: 'https://images.pexels.com/photos/7175438/pexels-photo-7175438.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'A traditional maroon kurta pajama set for boys in a comfortable cotton silk blend.',
    category: 'popular',
    demographic: 'boy',
    productType: 'kurta',
  },
  
  // More products
  {
    id: '10',
    name: 'Emerald Green Silk Saree',
    price: 280,
    image: 'https://images.pexels.com/photos/16147488/pexels-photo-16147488/free-photo-of-woman-in-red-sari-sitting-on-flower-petals.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'A luxurious emerald green Kanjeevaram silk saree with a contrasting border. A timeless classic.',
    category: 'best',
    demographic: 'women',
    productType: 'saree',
  },
  {
    id: '11',
    name: 'Black Velvet Sherwani',
    price: 400,
    image: 'https://images.pexels.com/photos/13136274/pexels-photo-13136274.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'A regal black velvet sherwani with intricate hand embroidery. Perfect for a winter wedding reception.',
    category: 'new',
    demographic: 'men',
    productType: 'sherwani',
  },
  {
    id: '12',
    name: 'Embroidered Blue Kurta',
    price: 95,
    image: 'https://images.pexels.com/photos/14792036/pexels-photo-14792036.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'A stylish blue linen kurta for men with chikankari embroidery. Perfect for a semi-formal look.',
    category: 'none',
    demographic: 'men',
    productType: 'kurta',
  },
];